#!/bin/bash
# =============================================================================
# linux_hardening.sh
# Wazuh-Automated Linux Endpoint Hardening Script
#
# Project: Automated Linux Endpoint Hardening with Wazuh
# Author:  Dimas Qi Ramadhani
#
# Description:
#   Applies a targeted set of CIS Ubuntu 24.04 benchmark remediations
#   for sysctl network parameters and /dev/shm mount options.
#   Designed to run via the Wazuh Command Module on a schedule.
#
# Design:
#   - IDEMPOTENT: checks current state before applying any change
#   - NON-DESTRUCTIVE: no user management, no SSH changes, no service removal
#   - AUDITABLE: all actions logged to /var/log/wazuh-linux-hardening.log
#   - BACKED UP: configuration files backed up before modification
#
# Location:  /var/ossec/active-response/bin/linux_hardening.sh
# Ownership: root:wazuh
# Permission: 750
#
# Usage (manual): sudo bash linux_hardening.sh
# Usage (Wazuh):  Wazuh Command Module runs this automatically
#
# ⚠️ LAB USE ONLY. Test in isolated environment before any production use.
#    Always take a VM snapshot before running hardening scripts.
# =============================================================================

set -euo pipefail

# =============================================================================
# Configuration
# =============================================================================
LOG_FILE="/var/log/wazuh-linux-hardening.log"
SYSCTL_CONF="/etc/sysctl.d/99-wazuh-hardening.conf"
BACKUP_DIR="/var/backups/wazuh-hardening"
TIMESTAMP=$(date '+%Y-%m-%dT%H:%M:%S')

# Counters
CHANGED=0
COMPLIANT=0
FAILED=0

# =============================================================================
# Logging
# =============================================================================
log() {
    local level="$1"
    local msg="$2"
    echo "[$TIMESTAMP] [$level] $msg" | tee -a "$LOG_FILE"
}

log_changed()    { log "CHANGED"    "$1"; ((CHANGED++))   || true; }
log_compliant()  { log "COMPLIANT"  "$1"; ((COMPLIANT++)) || true; }
log_failed()     { log "FAILED"     "$1"; ((FAILED++))    || true; }
log_info()       { log "INFO"       "$1"; }

# =============================================================================
# Root check
# =============================================================================
if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root." >&2
    exit 1
fi

log_info "=========================================="
log_info "Wazuh Linux Hardening Script Started"
log_info "Host: $(hostname)"
log_info "OS:   $(lsb_release -ds 2>/dev/null || cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2 | tr -d '\"')"
log_info "=========================================="

# =============================================================================
# Create backup directory
# =============================================================================
mkdir -p "$BACKUP_DIR"

# =============================================================================
# Backup configuration files
# =============================================================================
backup_file() {
    local src="$1"
    if [[ -f "$src" ]]; then
        local dest="${BACKUP_DIR}/$(basename $src).bak_$(date +%Y%m%d_%H%M%S)"
        cp "$src" "$dest"
        log_info "Backup created: $dest"
    fi
}

backup_file "/etc/sysctl.conf"
backup_file "/etc/fstab"

# =============================================================================
# Helper: apply sysctl setting
# =============================================================================
apply_sysctl() {
    local key="$1"
    local expected_value="$2"
    local description="$3"

    local current_value
    current_value=$(sysctl -n "$key" 2>/dev/null || echo "UNKNOWN")

    if [[ "$current_value" == "$expected_value" ]]; then
        log_compliant "LH: $description — $key = $expected_value (already compliant)"
    else
        if sysctl -w "${key}=${expected_value}" >> "$LOG_FILE" 2>&1; then
            log_changed "LH: $description — $key set to $expected_value (was: $current_value)"
            # Write to persistent config
            echo "${key} = ${expected_value}" >> "${SYSCTL_CONF}.tmp"
        else
            log_failed "LH: $description — Failed to set $key"
        fi
    fi
}

# =============================================================================
# Prepare sysctl persistent config
# =============================================================================
log_info "Writing sysctl hardening configuration..."
cat > "${SYSCTL_CONF}.tmp" << 'SYSCTL_HEADER'
# =============================================================
# Wazuh Automated Linux Hardening
# CIS Ubuntu 24.04 Benchmark — Network Parameter Hardening
# Generated by linux_hardening.sh
# =============================================================

SYSCTL_HEADER

# =============================================================================
# LH-002: Disable packet redirect sending
# CIS: 3.1.2 — Ensure packet redirect sending is disabled
# Risk: Prevents this host from sending ICMP redirects that could
#       manipulate routing on adjacent hosts.
# =============================================================================
log_info "--- LH-002: Disable packet redirect sending ---"
apply_sysctl "net.ipv4.conf.all.send_redirects"     "0" "Disable send_redirects (all)"
apply_sysctl "net.ipv4.conf.default.send_redirects" "0" "Disable send_redirects (default)"

# =============================================================================
# LH-003: Disable IP forwarding
# CIS: 3.1.1 — Ensure IP forwarding is disabled
# Risk: Prevents this endpoint from acting as a network router.
#       Only disable on endpoints that do not need to forward traffic.
# =============================================================================
log_info "--- LH-003: Disable IP forwarding ---"
apply_sysctl "net.ipv4.ip_forward" "0" "Disable IPv4 IP forwarding"

# =============================================================================
# LH-004: Disable source routed packets
# CIS: 3.2.1 — Ensure source routed packets are not accepted
# Risk: Source routing can be used to bypass firewall rules and
#       conduct IP spoofing attacks.
# =============================================================================
log_info "--- LH-004: Disable source routed packets ---"
apply_sysctl "net.ipv4.conf.all.accept_source_route"     "0" "Disable accept_source_route (all)"
apply_sysctl "net.ipv4.conf.default.accept_source_route" "0" "Disable accept_source_route (default)"

# =============================================================================
# LH-005: Disable ICMP redirects
# CIS: 3.2.2 — Ensure ICMP redirects are not accepted
# Risk: ICMP redirects can be used to alter routing tables and
#       redirect traffic through attacker-controlled paths.
# =============================================================================
log_info "--- LH-005: Disable ICMP redirects ---"
apply_sysctl "net.ipv4.conf.all.accept_redirects"     "0" "Disable accept_redirects (all)"
apply_sysctl "net.ipv4.conf.default.accept_redirects" "0" "Disable accept_redirects (default)"

# =============================================================================
# LH-006: Disable secure ICMP redirects
# CIS: 3.2.3 — Ensure secure ICMP redirects are not accepted
# Risk: Even redirects from gateways listed as default gateways
#       can be abused. Disable for stricter network hardening.
# =============================================================================
log_info "--- LH-006: Disable secure ICMP redirects ---"
apply_sysctl "net.ipv4.conf.all.secure_redirects"     "0" "Disable secure_redirects (all)"
apply_sysctl "net.ipv4.conf.default.secure_redirects" "0" "Disable secure_redirects (default)"

# =============================================================================
# Write and apply sysctl config
# =============================================================================
if [[ -f "${SYSCTL_CONF}.tmp" ]]; then
    mv "${SYSCTL_CONF}.tmp" "$SYSCTL_CONF"
    log_info "sysctl config written: $SYSCTL_CONF"
    if sysctl --system >> "$LOG_FILE" 2>&1; then
        log_info "sysctl --system applied successfully"
    else
        log_failed "sysctl --system failed — check $LOG_FILE"
    fi
fi

# =============================================================================
# LH-001: /dev/shm mount hardening
# CIS: 1.1.8, 1.1.9, 1.1.10 — Ensure noexec,nodev,nosuid on /dev/shm
# Risk: /dev/shm is shared memory mounted as tmpfs. Without hardening,
#       it can be used to execute arbitrary code or create device files.
# =============================================================================
log_info "--- LH-001: /dev/shm mount options ---"

REQUIRED_OPTS="noexec,nodev,nosuid"
CURRENT_OPTS=$(mount | grep "/dev/shm" | grep -oP '(?<=\().*(?=\))' | head -1)

if echo "$CURRENT_OPTS" | grep -q "noexec" && \
   echo "$CURRENT_OPTS" | grep -q "nodev"  && \
   echo "$CURRENT_OPTS" | grep -q "nosuid"; then
    log_compliant "LH-001: /dev/shm already has $REQUIRED_OPTS"
else
    log_info "LH-001: /dev/shm current options: $CURRENT_OPTS"
    log_info "LH-001: Updating /etc/fstab for /dev/shm..."

    # Check if /dev/shm entry exists in fstab
    if grep -q "shm\|/dev/shm" /etc/fstab; then
        # Update existing entry
        sed -i.bak_wazuh "s|^\(tmpfs\s\+/dev/shm.*\)|\1,${REQUIRED_OPTS}|" /etc/fstab
        log_info "LH-001: Updated existing /dev/shm fstab entry"
    else
        # Add new entry
        echo "tmpfs   /dev/shm   tmpfs   defaults,${REQUIRED_OPTS}   0 0" >> /etc/fstab
        log_info "LH-001: Added /dev/shm entry to /etc/fstab"
    fi

    # Remount to apply immediately
    if mount -o remount /dev/shm 2>> "$LOG_FILE"; then
        log_changed "LH-001: /dev/shm remounted with $REQUIRED_OPTS"
    else
        log_info "LH-001: fstab updated — reboot or manual remount required to take full effect"
    fi
fi

# =============================================================================
# Summary
# =============================================================================
log_info "=========================================="
log_info "Hardening Script Completed"
log_info "Changed:   $CHANGED"
log_info "Compliant: $COMPLIANT"
log_info "Failed:    $FAILED"
log_info "Backup:    $BACKUP_DIR"
log_info "Log:       $LOG_FILE"
log_info "Sysctl:    $SYSCTL_CONF"
log_info "=========================================="

if [[ $FAILED -gt 0 ]]; then
    exit 2
else
    exit 0
fi
